#%RAML 1.0 NamedExample
product:
-
  productId: 123
  productCategory: abc
  productName:    xyz
  sellingcost: 1234
 
-
  productId: 123
  productCategory: abc
  productName:    xyz
  sellingcost: 1234
 
  